on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: JDK Configuration
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Build app
        run: mvn package

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: JDK Configuration
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Run testes
        run: mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'release'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: JDK Configuration
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Instalar Maven
        run: sudo apt-get install -y maven

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener .

      - name: Extract tag name or release
        id: extract_tag
        run: echo "::set-output name=tag::$(echo ${{ github.ref }} | cut -d '/' -f 3)"

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:${{ steps.extract_tag.outputs.tag }}

      - name: Send Imagem to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:${{ steps.extract_tag.outputs.tag }}